### ISSUE TITLE
Docker 1.* does not respect non-default build context settings like 0.*

### ISSUE THREAD

**Issue by cmeyertons** [Microsoft/vsts-docker#49]
My YAML:

```
- task: Docker@1
  displayName: 'Build api dockerfile'
  inputs:
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '{"loginServer":"$(azureContainerRegistry)", "id" : "$(acrServiceEndpoint)"}'
    imageName: '$(azureContainerRegistry)/my_image:$(tagName)'
    dockerFile: api/docker/api/Dockerfile
    command: build
    includeSourceTags: true
    includeLatestTag: true
    defaultContext: false
    context: api
    addDefaultLabels: true
```

if I change the task back to `Docker@0`, the build succeeds
