### ISSUE TITLE
v1.* Push multiple images doesn't support VSTS variable substitution

### ISSUE THREAD

**Issue by cmeyertons** [Microsoft/vsts-docker#50]
YAML:
```
- task: Docker@1
  displayName: 'Push api, kibana, and elastisearch'
  inputs:
    azureSubscriptionEndpoint: '$(azureSubscription)'
    azureContainerRegistry: '{"loginServer":"$(azureContainerRegistry)", "id" : "$(acrServiceEndpoint)"}'
    command: 'push'
    includeSourceTags: true
    includeLatestTag: true
    pushMultipleImages: true
    imageNamesPath: "api/docker/images.txt"
```

api/docker/images.txt:
```
$(azureContainerRegistry)/myimage1_backend_elasticsearch:$(tagName)
$(azureContainerRegistry)/myimage2_backend_kibana:$(tagName)
$(azureContainerRegistry)/myimage3_backend_api:$(tagName)
```

VSTS error log:
```
2018-10-16T12:05:44.6311900Z [command]/usr/local/bin/docker push lowecoacr.azurecr.io/$(azurecontainerregistry)/myimage1_elasticsearch:$(tagname)
2018-10-16T12:05:44.6312712Z invalid reference format
2018-10-16T12:05:44.6362950Z ##[error]invalid reference format
2018-10-16T12:05:44.6371716Z ##[error]/usr/local/bin/docker failed with return code: 1
```

with the new yaml experience, i'm not sure if having to define a file outside of your pipeline is necessarily the best experience.  it would be very nice if there was a imageNames collection parameter, or if imageName accepted a collection?

```
pushMultipleImages: true
imageNames:
  - $(azureContainerRegistry)/myimage1_backend_elasticsearch:$(tagName)
  - $(azureContainerRegistry)/myimage2_backend_kibana:$(tagName)
  - $(azureContainerRegistry)/myimage3_backend_api:$(tagName)
```
